@startuml  ホテル予約システム

left to right direction

actor 利用者
actor ホテル従業員
actor ホテル管理者

rectangle ホテル予約システム {
  利用者 --> (ホテルの空室状況を閲覧する)
  利用者 --> (<u>ホテルの部屋を予約する\n拡張点\nキャンペーン期間)
  利用者 --> (会員登録を行う)

  (空室状況を入力する) <-- ホテル従業員

  (予約の集計を行う) <-- ホテル管理者

  (ログインする) <-- 利用者
  (ログインする) <-- ホテル従業員
  (ログインする) <-- ホテル管理者

  (キャンペーン価格にする) .> (<u>ホテルの部屋を予約する\n拡張点\nキャンペーン期間) : <<extend>>
  (<u>ホテルの部屋を予約する\n拡張点\nキャンペーン期間) .> (ログインする) : << include >>
}

@enduml
